#! /usr/bin/env bash

http POST http://localhost:8080/book title="Il Signore degli Anelli" author="John Ronald Reuel Tolkien"
http POST http://localhost:8080/book title="Fiabe" author="Hans Christian Andersen"
http POST http://localhost:8080/book title="Divina Commedia" author="Dante Alighieri"
http POST http://localhost:8080/book title="Epopea di Gilgameš" author="anonimo"
http POST http://localhost:8080/book title="Libro di Giobbe" author="anonimo"
http POST http://localhost:8080/book title="Le mille e una notte" author="anonimo"
http POST http://localhost:8080/book title="Njáls saga" author="anonimo"
http POST http://localhost:8080/book title="Orgoglio e pregiudizio" author="Jane Austen"
http POST http://localhost:8080/book title="Papà Goriot" author="Honoré de Balzac"
http POST http://localhost:8080/book title="Molloy, Malone muore, L'innominabile" author="Samuel Beckett"
http POST http://localhost:8080/book title="Decameron" author="Giovanni Boccaccio"
http POST http://localhost:8080/book title="Finzioni" author="Jorge Luis Borges"
http POST http://localhost:8080/book title="Cime tempestose" author="Emily Brontë"
http POST http://localhost:8080/book title="Lo straniero" author="Albert Camus"
http POST http://localhost:8080/book title="Poesie" author="Paul Celan"
http POST http://localhost:8080/book title="Viaggio al termine della notte" author="Louis-Ferdinand Céline"
http POST http://localhost:8080/book title="Don Chisciotte della Mancia" author="Miguel de Cervantes"
http POST http://localhost:8080/book title="I racconti di Canterbury" author="Geoffrey Chaucer"
http POST http://localhost:8080/book title="Racconti" author="Anton Čechov"
http POST http://localhost:8080/book title="Nostromo" author="Joseph Conrad"
http POST http://localhost:8080/book title="Grandi speranze" author="Charles Dickens"
http POST http://localhost:8080/book title="Jacques il fatalista" author="Denis Diderot"
http POST http://localhost:8080/book title="Berlin Alexanderplatz" author="Alfred Döblin"
http POST http://localhost:8080/book title="Delitto e castigo" author="Fëdor Dostoevskij"
http POST http://localhost:8080/book title="L'idiota" author="Fëdor Dostoevskij"
http POST http://localhost:8080/book title="I demoni" author="Fëdor Dostoevskij"
http POST http://localhost:8080/book title="I fratelli Karamazov" author="Fëdor Dostoevskij"
http POST http://localhost:8080/book title="Middlemarch" author="George Eliot"
http POST http://localhost:8080/book title="Uomo invisibile" author="Ralph Ellison"
http POST http://localhost:8080/book title="Medea" author="Euripide"
http POST http://localhost:8080/book title="Assalonne, Assalonne!" author="William Faulkner"
http POST http://localhost:8080/book title="L'urlo e il furore" author="William Faulkner"
http POST http://localhost:8080/book title="Madame Bovary" author="Gustave Flaubert"
http POST http://localhost:8080/book title="L'educazione sentimentale" author="Gustave Flaubert"
http POST http://localhost:8080/book title="Romancero gitano" author="Federico García Lorca"
http POST http://localhost:8080/book title="Cent'anni di solitudine" author="Gabriel García Márquez"
http POST http://localhost:8080/book title="L'amore ai tempi del colera" author="Gabriel García Márquez"
http POST http://localhost:8080/book title="Faust" author="Johann Wolfgang von Goethe"
http POST http://localhost:8080/book title="Le anime morte" author="Nikolaj Vasil'evič Gogol'"
http POST http://localhost:8080/book title="Il tamburo di latta" author="Günter Grass"
http POST http://localhost:8080/book title="Grande Sertão" author="João Guimarães Rosa"
http POST http://localhost:8080/book title="Fame" author="Knut Hamsun"
http POST http://localhost:8080/book title="Il vecchio e il mare" author="Ernest Hemingway"
http POST http://localhost:8080/book title="Casa di bambola" author="Henrik Ibsen"
http POST http://localhost:8080/book title="Ulisse" author="James Joyce"
http POST http://localhost:8080/book title="La metamorfosi ed altri racconti" author="Franz Kafka"
http POST http://localhost:8080/book title="Il processo" author="Franz Kafka"
http POST http://localhost:8080/book title="Il castello" author="Franz Kafka"
http POST http://localhost:8080/book title="Abhijñānaśākuntalam" author="Kālidāsa"
http POST http://localhost:8080/book title="Il suono della montagna" author="Yasunari Kawabata"
http POST http://localhost:8080/book title="Zorba il greco" author="Nikos Kazantzakis"
http POST http://localhost:8080/book title="Figli e amanti" author="David Herbert Lawrence"
http POST http://localhost:8080/book title="Gente indipendente" author="Halldór Laxness"
http POST http://localhost:8080/book title="Operette Morali" author="Giacomo Leopardi"
http POST http://localhost:8080/book title="Il taccuino d'oro" author="Doris Lessing"
http POST http://localhost:8080/book title="Pippi Calzelunghe" author="Astrid Lindgren"
http POST http://localhost:8080/book title="Diario di un pazzo" author="Lu Hsun"
http POST http://localhost:8080/book title="Il rione dei ragazzi" author="Naguib Mahfouz"
http POST http://localhost:8080/book title="I Buddenbrook" author="Thomas Mann"
http POST http://localhost:8080/book title="La montagna incantata" author="Thomas Mann"
http POST http://localhost:8080/book title="Moby-Dick" author="Herman Melville"
http POST http://localhost:8080/book title="Saggi" author="Michel de Montaigne"
http POST http://localhost:8080/book title="La Storia" author="Elsa Morante"
http POST http://localhost:8080/book title="Amatissima" author="Toni Morrison"
http POST http://localhost:8080/book title="Genji monogatari" author="Murasaki Shikibu"
http POST http://localhost:8080/book title="L'uomo senza qualità" author="Robert Musil"
http POST http://localhost:8080/book title="Canti" author="Giacomo Leopardi"
http POST http://localhost:8080/book title="Lolita" author="Vladimir Nabokov"
http POST http://localhost:8080/book title="Iliade" author="Omero"
http POST http://localhost:8080/book title="Odissea" author="Omero"
http POST http://localhost:8080/book title="1984" author="George Orwell"
http POST http://localhost:8080/book title="Le metamorfosi" author="Ovidio"
http POST http://localhost:8080/book title="Libro dell'inquietudine" author="Fernando Pessoa"
http POST http://localhost:8080/book title="Racconti" author="Edgar Allan Poe"
http POST http://localhost:8080/book title="Alla ricerca del tempo perduto" author="Marcel Proust"
http POST http://localhost:8080/book title="Gargantua e Pantagruel" author="François Rabelais"
http POST http://localhost:8080/book title="Pedro Páramo" author="Juan Rulfo"
http POST http://localhost:8080/book title="Mathnawi" author="Gialal al-Din Rumi"
http POST http://localhost:8080/book title="I figli della mezzanotte" author="Salman Rushdie"
http POST http://localhost:8080/book title="Bustan" author="Saadi"
http POST http://localhost:8080/book title="La stagione della migrazione a Nord" author="Tayeb Salih"
http POST http://localhost:8080/book title="Cecità" author="José Saramago"
http POST http://localhost:8080/book title="Amleto" author="William Shakespeare"
http POST http://localhost:8080/book title="Re Lear" author="William Shakespeare"
http POST http://localhost:8080/book title="Otello" author="William Shakespeare"
http POST http://localhost:8080/book title="Edipo re" author="Sofocle"
http POST http://localhost:8080/book title="Il rosso e il nero" author="Stendhal"
http POST http://localhost:8080/book title="Vita e opinioni di Tristram Shandy, gentiluomo" author="Laurence Sterne"
http POST http://localhost:8080/book title="La coscienza di Zeno" author="Italo Svevo"
http POST http://localhost:8080/book title="I viaggi di Gulliver" author="Jonathan Swift"
http POST http://localhost:8080/book title="Guerra e pace" author="Lev Tolstoj"
http POST http://localhost:8080/book title="Anna Karenina" author="Lev Tolstoj"
http POST http://localhost:8080/book title="La morte di Ivan Il'ič" author="Lev Tolstoj"
http POST http://localhost:8080/book title="Le avventure di Huckleberry Finn" author="Mark Twain"
http POST http://localhost:8080/book title="Rāmāyaṇa" author="Vālmīki"
http POST http://localhost:8080/book title="Eneide" author="Virgilio"
http POST http://localhost:8080/book title="Mahābhārata" author="Vyāsa"
http POST http://localhost:8080/book title="Foglie d'erba" author="Walt Whitman"
http POST http://localhost:8080/book title="La signora Dalloway" author="Virginia Woolf"
http POST http://localhost:8080/book title="Gita al faro" author="Virginia Woolf"
http POST http://localhost:8080/book title="Memorie di Adriano" author="Marguerite Yourcenar"